# Generated by Django 5.1 on 2024-09-05 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_requirements'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'jobseeker')},
        ),
    ]
