# Generated by Django 5.1 on 2024-09-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_employer_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/blank.png', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/blank.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
