# Generated by Django 5.1 on 2024-09-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_employer_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='profile_picture',
        ),
    ]
