# Generated by Django 5.1 on 2024-09-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_employer_profile_picture_jobseeker_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='current_job',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='work_experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
